# Generated by Django 3.1.3 on 2020-12-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
