# Generated by Django 3.1.3 on 2020-12-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicetype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='volume_type',
            field=models.CharField(choices=[('HOUR', 'Hour'), ('LIMIT', 'Limit')], max_length=100),
        ),
    ]
