# Generated by Django 3.1.3 on 2020-12-29 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201228_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
