# Generated by Django 3.1.3 on 2021-01-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210102_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='role',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='verifytoken',
            name='uid',
        ),
    ]
