# Generated by Django 3.1.3 on 2021-01-03 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_packagevalidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete')),
                ('name', models.CharField(max_length=500)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_package_created', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to='core.Service')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_package_updated', to=settings.AUTH_USER_MODEL)),
                ('validity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.packagevalidity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
