# Generated by Django 3.1.3 on 2021-01-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210123_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
