# Generated by Django 3.1.3 on 2021-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20210123_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
